// Synthetic series are generated by index-based AR recurrences (y[t] from
// y[t-1], x[t-1]), for which a range loop is the natural form.
#![allow(clippy::needless_range_loop)]
use super::*;

/// Deterministic splitmix64 → uniform f64 in [0,1); reproducible noise, no RNG.
fn splitmix(mut x: u64) -> f64 {
    x = x.wrapping_add(0x9E37_79B9_7F4A_7C15);
    let mut z = x;
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^= z >> 31;
    ((z >> 11) as f64) / ((1_u64 << 53) as f64)
}

#[test]
fn detects_true_directional_causation() {
    // y_t = 0.5·y_{t-1} + 1.5·x_{t-1} + small noise; x is exogenous noise.
    // X drives Y with a one-step lag → X→Y strongly significant, Y↛X not.
    let n = 120;
    let mut x = vec![0.0f32; n];
    let mut y = vec![0.0f32; n];
    for t in 0..n {
        x[t] = (splitmix(t as u64) - 0.5) as f32;
    }
    for t in 1..n {
        let noise = (splitmix(1000 + t as u64) - 0.5) * 0.2;
        y[t] = 0.5 * y[t - 1] + 1.5 * x[t - 1] + noise as f32;
    }
    let fwd = granger_causality(&x, &y).unwrap();
    let rev = granger_causality(&y, &x).unwrap();
    assert!(fwd.p_value < 0.001, "X→Y must be significant: {fwd:?}");
    assert!(rev.p_value > 0.05, "Y→X must be insignificant: {rev:?}");
    assert!(
        fwd.rss_unrestricted < fwd.rss_restricted,
        "x-lags improve fit: {fwd:?}"
    );
}

#[test]
fn independent_series_is_insignificant() {
    let n = 100;
    let mut x = vec![0.0f32; n];
    let mut y = vec![0.0f32; n];
    for t in 0..n {
        x[t] = (splitmix(t as u64) - 0.5) as f32;
        y[t] = (splitmix(7777 + t as u64) - 0.5) as f32;
    }
    let g = granger_causality(&x, &y).unwrap();
    assert!(g.p_value > 0.05, "independent → insignificant: {g:?}");
}

#[test]
fn f_statistic_matches_independent_ols() {
    // Locked against an independent numpy `lstsq` OLS on the SAME lagged
    // design: for this fixed 12-point series at p=1,
    //   T = 11, RSS_r = 96.909059, RSS_u = 1.330807, df = (1, 8),
    //   F = 574.5581, upper-tail p = 9.78e-9.
    let x = [
        1.0f32, 3.0, 2.0, 5.0, 4.0, 7.0, 6.0, 9.0, 8.0, 11.0, 10.0, 13.0,
    ];
    let y = [
        2.0f32, 1.0, 5.0, 4.0, 8.0, 6.0, 11.0, 9.0, 14.0, 12.0, 17.0, 15.0,
    ];
    let g = granger_causality_lags(&x, &y, 1).unwrap();
    assert_eq!(g.df_num, 1);
    assert_eq!(g.df_den, 8);
    assert_eq!(g.n_used, 11);
    assert!((g.rss_restricted - 96.909_06).abs() < 1e-2, "RSS_r: {g:?}");
    assert!(
        (g.rss_unrestricted - 1.330_807).abs() < 1e-3,
        "RSS_u: {g:?}"
    );
    // Large F; assert to a relative tolerance and a decisive p.
    assert!((g.f_statistic - 574.558).abs() / 574.558 < 1e-3, "F: {g:?}");
    assert!(g.p_value < 1e-6, "p decisive: {g:?}");
}

#[test]
fn sweep_selects_the_planted_lag() {
    // Plant the driver at a two-step lag: y_t = 0.4·y_{t-1} + 1.5·x_{t-2}.
    // The sweep over [1,2,4,8] should pick lag 2 as the max-effect lag.
    let n = 160;
    let mut x = vec![0.0f32; n];
    let mut y = vec![0.0f32; n];
    for t in 0..n {
        x[t] = (splitmix(t as u64) - 0.5) as f32;
    }
    for t in 2..n {
        let noise = (splitmix(2000 + t as u64) - 0.5) * 0.15;
        y[t] = 0.4 * y[t - 1] + 1.5 * x[t - 2] + noise as f32;
    }
    let best = granger_causality_sweep(&x, &y).unwrap();
    assert_eq!(
        best.lags, 2,
        "sweep must find the planted lag-2 driver: {best:?}"
    );
    assert!(best.p_value < 0.001, "planted lag significant: {best:?}");
}

#[test]
fn fails_closed_on_zero_lags() {
    assert_eq!(
        granger_causality_lags(&[1.0, 2.0, 3.0, 4.0, 5.0], &[1.0, 2.0, 3.0, 4.0, 5.0], 0)
            .unwrap_err()
            .code,
        "CALYX_ASSAY_INSUFFICIENT_SAMPLES"
    );
}

#[test]
fn fails_closed_on_length_mismatch() {
    assert_eq!(
        granger_causality(&[1.0, 2.0, 3.0, 4.0, 5.0], &[1.0, 2.0, 3.0])
            .unwrap_err()
            .code,
        "CALYX_ASSAY_INSUFFICIENT_SAMPLES"
    );
}

#[test]
fn fails_closed_below_min_samples() {
    // p=1 needs n ≥ 5; give 4.
    assert_eq!(
        granger_causality_lags(&[1.0, 2.0, 3.0, 4.0], &[2.0, 1.0, 4.0, 3.0], 1)
            .unwrap_err()
            .code,
        "CALYX_ASSAY_INSUFFICIENT_SAMPLES"
    );
}

#[test]
fn fails_closed_on_non_finite() {
    let mut x = vec![1.0f32; 20];
    x[5] = f32::NAN;
    let y: Vec<f32> = (0..20).map(|i| i as f32).collect();
    assert_eq!(
        granger_causality(&x, &y).unwrap_err().code,
        "CALYX_ASSAY_INSUFFICIENT_SAMPLES"
    );
}

#[test]
fn fails_closed_on_constant_regressor() {
    // Constant y → restricted design has collinear [1, y_{t-1}] columns →
    // rank-deficient normal equations → degenerate.
    let x: Vec<f32> = (0..20).map(|i| (i % 3) as f32).collect();
    let y = vec![4.0f32; 20];
    assert_eq!(
        granger_causality(&x, &y).unwrap_err().code,
        "CALYX_ASSAY_DEGENERATE_INPUT"
    );
}
