// === Perception (06 section 8.1) ===
pub const OBSERVE_NO_PERCEPTION_AVAILABLE: &str = "OBSERVE_NO_PERCEPTION_AVAILABLE";
pub const OBSERVE_INTERNAL: &str = "OBSERVE_INTERNAL";
pub const CAPTURE_GRAPHICS_API_UNSUPPORTED: &str = "CAPTURE_GRAPHICS_API_UNSUPPORTED";
pub const CAPTURE_TARGET_LOST: &str = "CAPTURE_TARGET_LOST";
pub const CAPTURE_NO_DIRTY_REGIONS: &str = "CAPTURE_NO_DIRTY_REGIONS";
pub const A11Y_NOT_AVAILABLE: &str = "A11Y_NOT_AVAILABLE";
pub const A11Y_ELEMENT_STALE: &str = "A11Y_ELEMENT_STALE";
pub const A11Y_NO_FOREGROUND: &str = "A11Y_NO_FOREGROUND";
pub const A11Y_CDP_UNREACHABLE: &str = "A11Y_CDP_UNREACHABLE";
pub const DETECTION_MODEL_NOT_LOADED: &str = "DETECTION_MODEL_NOT_LOADED";
pub const DETECTION_MODEL_INFER_FAILED: &str = "DETECTION_MODEL_INFER_FAILED";
pub const DETECTION_NO_FRAME: &str = "DETECTION_NO_FRAME";
pub const OCR_NO_TEXT: &str = "OCR_NO_TEXT";
pub const OCR_BACKEND_UNAVAILABLE: &str = "OCR_BACKEND_UNAVAILABLE";
pub const HUD_NO_ACTIVE_PROFILE: &str = "HUD_NO_ACTIVE_PROFILE";
pub const HUD_FIELD_NOT_DEFINED: &str = "HUD_FIELD_NOT_DEFINED";
pub const HUD_EXTRACTION_FAILED: &str = "HUD_EXTRACTION_FAILED";
pub const AUDIO_DEVICE_LOST: &str = "AUDIO_DEVICE_LOST";
pub const AUDIO_LOOPBACK_INIT_FAILED: &str = "AUDIO_LOOPBACK_INIT_FAILED";
pub const AUDIO_STT_MODEL_NOT_LOADED: &str = "AUDIO_STT_MODEL_NOT_LOADED";

// === Action (06 section 8.2) ===
pub const ACTION_QUEUE_FULL: &str = "ACTION_QUEUE_FULL";
pub const ACTION_RATE_LIMITED: &str = "ACTION_RATE_LIMITED";
pub const ACTION_BACKEND_UNAVAILABLE: &str = "ACTION_BACKEND_UNAVAILABLE";
pub const ACTION_TARGET_INVALID: &str = "ACTION_TARGET_INVALID";
pub const ACTION_HOLD_EXCEEDED_MAX: &str = "ACTION_HOLD_EXCEEDED_MAX";
pub const ACTION_HID_PORT_DISCONNECTED: &str = "ACTION_HID_PORT_DISCONNECTED";
pub const ACTION_VIGEM_NOT_INSTALLED: &str = "ACTION_VIGEM_NOT_INSTALLED";
pub const ACTION_VIGEM_PLUGIN_FAILED: &str = "ACTION_VIGEM_PLUGIN_FAILED";
pub const ACTION_ELEMENT_NOT_RESOLVED: &str = "ACTION_ELEMENT_NOT_RESOLVED";
pub const ACTION_FOREGROUND_LOST: &str = "ACTION_FOREGROUND_LOST";
pub const ACTION_UNSUPPORTED_KEY: &str = "ACTION_UNSUPPORTED_KEY";
pub const ACTION_DRAG_DISTANCE_EXCEEDS_LIMIT: &str = "ACTION_DRAG_DISTANCE_EXCEEDS_LIMIT";
pub const STUCK_KEY_AUTO_RELEASED: &str = "STUCK_KEY_AUTO_RELEASED";
pub const SAFETY_RELEASE_ALL_FIRED: &str = "SAFETY_RELEASE_ALL_FIRED";
pub const SAFETY_OPERATOR_HOTKEY_FIRED: &str = "SAFETY_OPERATOR_HOTKEY_FIRED";

// === Reflex (06 section 8.3) ===
pub const REFLEX_CAP_REACHED: &str = "REFLEX_CAP_REACHED";
pub const REFLEX_KIND_INVALID: &str = "REFLEX_KIND_INVALID";
pub const REFLEX_PARAMS_INVALID: &str = "REFLEX_PARAMS_INVALID";
pub const REFLEX_TARGET_INVALID: &str = "REFLEX_TARGET_INVALID";
pub const REFLEX_FILTER_INVALID: &str = "REFLEX_FILTER_INVALID";
pub const REFLEX_PRIORITY_INVALID: &str = "REFLEX_PRIORITY_INVALID";
pub const REFLEX_TICK_LATE: &str = "REFLEX_TICK_LATE";
pub const REFLEX_TRACK_LOST: &str = "REFLEX_TRACK_LOST";
pub const REFLEX_STARVED: &str = "REFLEX_STARVED";
pub const REFLEX_DISABLED_BY_OPERATOR: &str = "REFLEX_DISABLED_BY_OPERATOR";
pub const REFLEX_LIFETIME_EXPIRED: &str = "REFLEX_LIFETIME_EXPIRED";

// === Profile and config (06 section 8.4) ===
pub const PROFILE_NOT_FOUND: &str = "PROFILE_NOT_FOUND";
pub const PROFILE_PARSE_ERROR: &str = "PROFILE_PARSE_ERROR";
pub const PROFILE_VERSION_INCOMPATIBLE: &str = "PROFILE_VERSION_INCOMPATIBLE";
pub const PROFILE_KEYMAP_INVALID: &str = "PROFILE_KEYMAP_INVALID";
pub const PROFILE_HUD_REGION_INVALID: &str = "PROFILE_HUD_REGION_INVALID";
pub const CAPTURE_TARGET_INVALID: &str = "CAPTURE_TARGET_INVALID";
pub const PERCEPTION_MODE_INVALID: &str = "PERCEPTION_MODE_INVALID";

// === MCP and session (06 section 8.5) ===
pub const SESSION_NOT_FOUND: &str = "SESSION_NOT_FOUND";
pub const SESSION_EXPIRED: &str = "SESSION_EXPIRED";
pub const SUBSCRIPTION_NOT_FOUND: &str = "SUBSCRIPTION_NOT_FOUND";
pub const SUBSCRIPTION_CAP_REACHED: &str = "SUBSCRIPTION_CAP_REACHED";
pub const TOOL_NOT_FOUND: &str = "TOOL_NOT_FOUND";
pub const TOOL_PARAMS_INVALID: &str = "TOOL_PARAMS_INVALID";
pub const TOOL_INTERNAL_ERROR: &str = "TOOL_INTERNAL_ERROR";

// === Storage (06 section 8.6) ===
pub const STORAGE_OPEN_FAILED: &str = "STORAGE_OPEN_FAILED";
pub const STORAGE_WRITE_FAILED: &str = "STORAGE_WRITE_FAILED";
pub const STORAGE_READ_FAILED: &str = "STORAGE_READ_FAILED";
pub const STORAGE_CORRUPTED: &str = "STORAGE_CORRUPTED";
pub const STORAGE_SCHEMA_MISMATCH: &str = "STORAGE_SCHEMA_MISMATCH";

// === Models (06 section 8.7) ===
pub const MODEL_DOWNLOAD_FAILED: &str = "MODEL_DOWNLOAD_FAILED";
pub const MODEL_HASH_MISMATCH: &str = "MODEL_HASH_MISMATCH";
pub const MODEL_LOAD_FAILED: &str = "MODEL_LOAD_FAILED";
pub const MODEL_BACKEND_UNAVAILABLE: &str = "MODEL_BACKEND_UNAVAILABLE";

// === Hardware HID (06 section 8.8) ===
pub const HID_PORT_NOT_FOUND: &str = "HID_PORT_NOT_FOUND";
pub const HID_PORT_OPEN_FAILED: &str = "HID_PORT_OPEN_FAILED";
pub const HID_PROTOCOL_HANDSHAKE_FAILED: &str = "HID_PROTOCOL_HANDSHAKE_FAILED";
pub const HID_FIRMWARE_VERSION_MISMATCH: &str = "HID_FIRMWARE_VERSION_MISMATCH";
pub const HID_COMMAND_REJECTED: &str = "HID_COMMAND_REJECTED";
pub const HID_LINK_TIMEOUT: &str = "HID_LINK_TIMEOUT";

// === Safety (06 section 8.9) ===
pub const SAFETY_KILLSWITCH_ACTIVE: &str = "SAFETY_KILLSWITCH_ACTIVE";
pub const SAFETY_PROCESS_DENYLISTED: &str = "SAFETY_PROCESS_DENYLISTED";
pub const SAFETY_SHELL_DENIED_BY_POLICY: &str = "SAFETY_SHELL_DENIED_BY_POLICY";
pub const SAFETY_LAUNCH_DENIED_BY_POLICY: &str = "SAFETY_LAUNCH_DENIED_BY_POLICY";
pub const SAFETY_SECRET_REDACTED: &str = "SAFETY_SECRET_REDACTED";
